import time
print("current time in sec:",time.time())
print("curremt time",time.ctime())
print("current time after 30 sec:",time.ctime(time.time()+30))
print()
t=time.localtime()
print("time t:",t)
print("current year:",t.tm_year)
print("current month:",t.tm_year)
print("current day:",t.tm_year)
print("current hour:",t.tm_year)
print("current year:",t.tm_year)
